### ISSUE TITLE
[request] README.md 파일 작성부탁드려요.

### ISSUE THREAD

**Issue by hyunsung-kim** [akfvhrl/myproject#1]
내용 구성은 잘 찾아 보시고 작성해 주시면 됩니다.
아래는 가능한 예제들입니다.

- Abstract
- Features
- Contributor
- License

**Comment by akfvhrl** [comment]
많이는 작성 못했지만 일단은 작성 시작했고, 앞으로 더 열심히 채워보겠습니다.

**Comment by hyunsung-kim** [comment]
수고하셨어요 :tada:
